name: Create GitHub Release

on:
  push:
    branches: [ main ]

jobs:
  build-windows-32:
    name: Build for Windows 32-bit
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 32-bit
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8'
          architecture: x86
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw32
          update: true
      - name: Install dependencies Win
        run: |
          pacman -S --noconfirm \
            mingw-w64-i686-gtk3 \
            mingw-w64-i686-gcc \
            mingw-w64-i686-python-pip \
            mingw-w64-i686-python3-gobject \
            mingw-w64-i686-poppler
      - name: Install dependencies Pip
        run: |
          python3 -m pip install pyinstaller
          python3 -m pip install -r requirements.txt
      - name: Check MSYS2 environment
        run: |
          echo "MSYSTEM=$MSYSTEM"
          echo "uname -m=$(uname -m)"
      - name: Set up environment
        run: |
          cp .env.ci .env
      - name: Build package
        run: |
          pyinstaller --distpath dist/windows build.spec
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: dist/windows/
